site_name: Pi Cluster Setup Documentation
site_description: Comprehensive guide for Raspberry Pi cluster setup
site_author: Jaeung Jang
plugins:
  - glightbox

theme:
  name: material
  palette:
    primary: deep orange
    accent: green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - Planning: planning.md
  - Hardware Setup: hardware.md
  - OS Setup: os-setup.md
  - Network Configuration: network.md
  - Kubernetes Setup: kubernetes.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true